# Project Ambrose by Imjustchico
# Runs a built server executable to check --version, a missing config, and --check with a copy of its shipped .conf.dist in the work folder, so no saved choice in the build folder's conf.d applies, where neither that run nor a run in Setup.Mode ask with ClientDir and TypeDumpPath empty and unlocked, an empty input file and a machine holding a synthetic install may print any text of a setup question to either output, the game and login servers must log that install as found with the advice for a run without a terminal, and no choice is saved; with AMBROSE_TEST_DB the game server and the login server, with its login and characters databases, create, update, open and close uniquely named databases that are dropped afterwards, the login server runs account commands piped into its console input, a bad login database string exits 1, the game server beats for the realm it was named as and leaves it offline when it stops, and the supervisor's --check names every app it would run and starts none of them, with its admin API on a port of its own choosing and its token in the work folder.
if(NOT APP OR NOT NAME OR NOT WORKDIR)
    message(FATAL_ERROR "APP, NAME and WORKDIR must be set")
endif()

execute_process(COMMAND "${APP}" --version RESULT_VARIABLE versionResult OUTPUT_VARIABLE versionOutput ERROR_VARIABLE versionError TIMEOUT 30)
if(NOT versionResult EQUAL 0)
    message(FATAL_ERROR "${NAME} --version exited ${versionResult}: ${versionOutput}${versionError}")
endif()
if(NOT versionOutput MATCHES "Project Ambrose rev ")
    message(FATAL_ERROR "${NAME} --version printed '${versionOutput}'")
endif()

file(REMOVE_RECURSE "${WORKDIR}")
file(MAKE_DIRECTORY "${WORKDIR}")
execute_process(COMMAND "${APP}" WORKING_DIRECTORY "${WORKDIR}" RESULT_VARIABLE missingResult OUTPUT_VARIABLE missingOutput ERROR_VARIABLE missingError TIMEOUT 30)
if(NOT missingResult EQUAL 1)
    message(FATAL_ERROR "${NAME} without a config exited ${missingResult}: ${missingOutput}${missingError}")
endif()
if(NOT missingError MATCHES "app-smoke[/\\\\]${NAME}[/\\\\]${NAME}\\.conf")
    message(FATAL_ERROR "${NAME} without a config did not name its full path: ${missingError}")
endif()
if(NOT missingError MATCHES "${NAME}\\.conf\\.dist")
    message(FATAL_ERROR "${NAME} without a config did not suggest copying ${NAME}.conf.dist: ${missingError}")
endif()

get_filename_component(appDir "${APP}" DIRECTORY)
include("${CMAKE_CURRENT_LIST_DIR}/TestDatabases.cmake")
set(portOption "${NAME}")
string(REPLACE "gameserver" "WorldServerPort" portOption "${portOption}")
string(REPLACE "loginserver" "LoginServerPort" portOption "${portOption}")
string(REPLACE "patchserver" "PatchServerPort" portOption "${portOption}")
set(quietOptions --set BindIP=127.0.0.1 --set ${portOption}=0 --set ClientDir= --set Appender.Server=1,3,0 --set Appender.Errors=1,3,0 --set Appender.Stream=1,3,0 --set Appender.Console=1,3,0)
if(NAME STREQUAL "supervisor")
    list(APPEND quietOptions --set Admin.Port=0 "--set=Admin.TokenFile=${WORKDIR}/admin.token")
endif()
set(questionText "needs your own Wizard101 install, and|needs the type dump made from your install, and|[Pp]ress Enter|\\[Y/n\\]|skipping setup questions|Type a path")
set(workConfig "${WORKDIR}/${NAME}.conf.dist")
file(COPY_FILE "${appDir}/${NAME}.conf.dist" "${workConfig}")
set(savedChoice "${WORKDIR}/conf.d/client-data.conf")
file(WRITE "${WORKDIR}/no-input.txt" "")
execute_process(COMMAND "${APP}" --check --config "${workConfig}" ${quietOptions} --set LoginDatabaseInfo= --set CharacterDatabaseInfo= --set WorldDatabaseInfo=
    WORKING_DIRECTORY "${WORKDIR}" INPUT_FILE "${WORKDIR}/no-input.txt" RESULT_VARIABLE distResult OUTPUT_VARIABLE distOutput ERROR_VARIABLE distError TIMEOUT 30)
if(NOT distResult EQUAL 0 OR NOT distOutput MATCHES "${NAME} ready" OR NOT distOutput MATCHES "${NAME} stopped" OR "${distOutput}${distError}" MATCHES "${questionText}")
    message(FATAL_ERROR "${NAME} with its shipped ${NAME}.conf.dist did not report ready without asking (${distResult}): ${distOutput}${distError}")
endif()
if(NAME STREQUAL "supervisor" AND (NOT distOutput MATCHES "Watching 3 app\\(s\\)" OR distOutput MATCHES "Started (loginserver|gameserver|patchserver)"))
    message(FATAL_ERROR "supervisor --check did not check its three apps without starting any: ${distOutput}${distError}")
endif()

set(machine "${WORKDIR}/machine")
set(synthetic "${machine}/drive_c/ProgramData/KingsIsle Entertainment/Wizard101")
file(WRITE "${synthetic}/Data/GameData/Root.wad" "not an archive")
file(WRITE "${synthetic}/Bin/revision.dat" "r999999999.Synthetic_1_0\n")
set(machineEnv "ProgramData=${machine}/drive_c/ProgramData" "WINEPREFIX=${machine}" "LOCALAPPDATA=${WORKDIR}/data" "XDG_DATA_HOME=${WORKDIR}/data" --unset=AMBROSE_CLIENT_DIR --unset=AMBROSE_TYPE_DUMP_PATH --unset=AMBROSE_SETUP_MODE)
set(askOptions --set BindIP=127.0.0.1 --set ${portOption}=0 --set Setup.Mode=ask --set Setup.PromptTimeout=5 --set Appender.Server=1,3,0 --set Appender.Errors=1,3,0 --set Appender.Stream=1,3,0 --set Appender.Console=1,3,0)
if(NAME STREQUAL "supervisor")
    list(APPEND askOptions --set Admin.Port=0 "--set=Admin.TokenFile=${WORKDIR}/admin.token")
endif()
execute_process(COMMAND "${CMAKE_COMMAND}" -E env ${machineEnv}
        "${APP}" --check --config "${workConfig}" ${askOptions} --set LoginDatabaseInfo= --set CharacterDatabaseInfo= --set WorldDatabaseInfo=
    WORKING_DIRECTORY "${WORKDIR}" INPUT_FILE "${WORKDIR}/no-input.txt" RESULT_VARIABLE askResult OUTPUT_VARIABLE askOutput ERROR_VARIABLE askError TIMEOUT 60)
if(NOT askResult EQUAL 0 OR NOT askOutput MATCHES "${NAME} ready" OR "${askOutput}${askError}" MATCHES "${questionText}")
    message(FATAL_ERROR "${NAME} in Setup.Mode ask with piped input did not start without asking (${askResult}): ${askOutput}${askError}")
endif()
if((NAME STREQUAL "gameserver" OR NAME STREQUAL "loginserver")
        AND (NOT "${askOutput}${askError}" MATCHES "ClientDir is not set, and Wizard101 was found on this machine: [^\n]*r999999999\\.Synthetic_1_0"
            OR NOT "${askOutput}${askError}" MATCHES "Start ${NAME} in a terminal whose input and output are not redirected to choose one"))
    message(FATAL_ERROR "${NAME} in Setup.Mode ask with piped input did not reach the setup questions with the synthetic install: ${askOutput}${askError}")
endif()
if(EXISTS "${savedChoice}")
    file(READ "${savedChoice}" savedText)
    message(FATAL_ERROR "${NAME} saved a setup choice to ${savedChoice} without being asked: ${savedText}")
endif()

if(NAME STREQUAL "loginserver" AND DEFINED ENV{AMBROSE_TEST_DB} AND NOT "$ENV{AMBROSE_TEST_DB}" STREQUAL "")
    ambrose_test_database_info(ambrose_smoke_login smokeDatabase)
    ambrose_test_database_info(ambrose_smoke_characters smokeCharacters)
    foreach(round IN ITEMS first second)
        execute_process(COMMAND "${APP}" --check --config "${appDir}/${NAME}.conf.dist" ${quietOptions} "--set=LoginDatabaseInfo=${smokeDatabase}" "--set=CharacterDatabaseInfo=${smokeCharacters}"
            WORKING_DIRECTORY "${WORKDIR}" RESULT_VARIABLE databaseResult OUTPUT_VARIABLE databaseOutput ERROR_VARIABLE databaseError TIMEOUT 60)
        if(NOT databaseResult EQUAL 0 OR NOT databaseOutput MATCHES "Opened database connection pool login: 1 async, 1 sync" OR NOT databaseOutput MATCHES "loginserver ready" OR NOT databaseOutput MATCHES "Closed database connection pool login"
            OR NOT databaseOutput MATCHES "Opened database connection pool characters: 1 async, 1 sync")
            ambrose_test_fail("loginserver with AMBROSE_TEST_DB did not update, open and close the login pool on its ${round} start (${databaseResult}): ${databaseOutput}${databaseError}")
        endif()
        if(round STREQUAL "first" AND (NOT databaseOutput MATCHES "Created database ambrose_smoke_login_" OR NOT databaseOutput MATCHES "importing 2 base file" OR NOT databaseOutput MATCHES "Applied RELEASED 2026_01_01_00\\.sql to the login database"
            OR NOT databaseOutput MATCHES "Created database ambrose_smoke_characters_" OR NOT databaseOutput MATCHES "Applied [0-9]+ update\\(s\\) to the characters database"))
            ambrose_test_fail("loginserver's first start did not create the login and characters databases, import the login base and apply their updates: ${databaseOutput}")
        endif()
    endforeach()
    if(NOT databaseOutput MATCHES "The login database is up to date" OR NOT databaseOutput MATCHES "The characters database is up to date")
        ambrose_test_fail("loginserver's second start did not report the login and characters databases up to date: ${databaseOutput}")
    endif()

    file(WRITE "${WORKDIR}/console.txt" "help account\naccount create smoke_user smoke_secret\naccount create SMOKE_USER smoke_secret\naccount info Smoke_User\nshutdown\n")
    execute_process(COMMAND "${CMAKE_COMMAND}" -E cat "${WORKDIR}/console.txt"
        COMMAND "${APP}" --config "${appDir}/${NAME}.conf.dist" ${quietOptions} "--set=LoginDatabaseInfo=${smokeDatabase}" "--set=CharacterDatabaseInfo=${smokeCharacters}"
        WORKING_DIRECTORY "${WORKDIR}" RESULT_VARIABLE consoleResult OUTPUT_VARIABLE consoleOutput ERROR_VARIABLE consoleError TIMEOUT 60)
    if(NOT consoleResult EQUAL 0)
        ambrose_test_fail("loginserver reading console commands exited ${consoleResult}: ${consoleOutput}${consoleError}")
    endif()
    foreach(expected IN ITEMS "account create <username> <password> \\[email\\] - create an account" "Account smoke_user created with id [0-9]+" "Account SMOKE_USER already exists"
            "Account smoke_user \\(id [0-9]+\\): security level 0, not locked, verifier key 0" "Not banned" "loginserver is shutting down"
            "Console: account create \\(arguments hidden\\)" "loginserver shutting down after the shutdown command" "loginserver stopped")
        if(NOT consoleOutput MATCHES "${expected}")
            ambrose_test_fail("loginserver's console run did not print '${expected}': ${consoleOutput}${consoleError}")
        endif()
    endforeach()
    if(consoleOutput MATCHES "smoke_secret" OR consoleError MATCHES "smoke_secret")
        ambrose_test_fail("loginserver's console run printed a password: ${consoleOutput}${consoleError}")
    endif()
endif()

function(ambrose_realm_step databaseInfo realmName testName what)
    execute_process(COMMAND "${CMAKE_COMMAND}" -E env "AMBROSE_TEST_DB=${databaseInfo}" "AMBROSE_REALM_NAME=${realmName}" "AMBROSE_REALM_MAX_AGE=180"
            "${UNIT_TESTS}" --gtest_also_run_disabled_tests "--gtest_filter=RealmHeartbeatIntegration.${testName}"
        RESULT_VARIABLE stepResult OUTPUT_VARIABLE stepOutput ERROR_VARIABLE stepError TIMEOUT 120)
    if(NOT stepResult EQUAL 0)
        ambrose_test_fail("the realm heartbeat check failed ${what} (${stepResult}): ${stepOutput}${stepError}")
    endif()
    if(NOT stepOutput MATCHES "PASSED[^
]*1 test")
        ambrose_test_fail("the realm heartbeat check did not run ${what}: ${stepOutput}${stepError}")
    endif()
endfunction()

if(NAME STREQUAL "gameserver" AND DEFINED ENV{AMBROSE_TEST_DB} AND NOT "$ENV{AMBROSE_TEST_DB}" STREQUAL "")
    set(realmOptions)
    foreach(database IN ITEMS Login Character World)
        string(TOLOWER "${database}" lowerDatabase)
        ambrose_test_database_info(ambrose_smoke_${lowerDatabase} databaseInfo)
        string(REPLACE ";" "\\;" databaseInfo "${databaseInfo}")
        list(APPEND realmOptions "--set=${database}DatabaseInfo=${databaseInfo}")
    endforeach()
    execute_process(COMMAND "${APP}" --check --config "${appDir}/${NAME}.conf.dist" ${quietOptions} ${realmOptions} --set Appender.DB=4,2,0
        WORKING_DIRECTORY "${WORKDIR}" RESULT_VARIABLE realmResult OUTPUT_VARIABLE realmOutput ERROR_VARIABLE realmError TIMEOUT 120)
    if(NOT realmResult EQUAL 0)
        ambrose_test_fail("gameserver --check on empty databases exited ${realmResult}: ${realmOutput}${realmError}")
    endif()

    if(UNIT_TESTS AND EXISTS "${UNIT_TESTS}")
        list(GET realmOptions 0 loginOption)
        string(REPLACE "--set=LoginDatabaseInfo=" "" loginInfo "${loginOption}")
        string(REPLACE "\;" ";" loginInfo "${loginInfo}")
        set(realmName "AmbroseSmoke")
        ambrose_realm_step("${loginInfo}" "${realmName}" DISABLED_AddTheRealmTheServerWillBeatFor "putting the realm in before the server ran")
        execute_process(COMMAND "${APP}" --check --config "${appDir}/${NAME}.conf.dist" ${quietOptions} ${realmOptions} --set Appender.DB=4,2,0
                "--set=Realm.Name=${realmName}"
            WORKING_DIRECTORY "${WORKDIR}" RESULT_VARIABLE beatResult OUTPUT_VARIABLE beatOutput ERROR_VARIABLE beatError TIMEOUT 120)
        if(NOT beatResult EQUAL 0)
            ambrose_test_fail("gameserver --check as realm ${realmName} exited ${beatResult}: ${beatOutput}${beatError}")
        endif()
        if(NOT beatOutput MATCHES "Realm ${realmName} says it is alive")
            ambrose_test_fail("gameserver as realm ${realmName} did not say it beats: ${beatOutput}${beatError}")
        endif()
        ambrose_realm_step("${loginInfo}" "${realmName}" DISABLED_TheRealmBeatWhileItRanAndIsOfflineNow "reading the realm back after the server stopped")
    endif()
    foreach(expected IN ITEMS "Created database ambrose_smoke_login_" "Created database ambrose_smoke_character_" "Created database ambrose_smoke_world_"
            "The login database is up to date|Applied [0-9]+ update\\(s\\) to the login database"
            "Applied [0-9]+ update\\(s\\) to the characters database" "Applied [0-9]+ update\\(s\\) to the world database"
            "Opened database connection pool world: 1 async, 1 sync" "The world database holds no character name tables" "gameserver ready" "Closed database connection pool world" "gameserver stopped")
        if(NOT realmOutput MATCHES "${expected}")
            ambrose_test_fail("gameserver on empty databases did not log '${expected}': ${realmOutput}${realmError}")
        endif()
    endforeach()
endif()
ambrose_drop_test_databases()

if(NAME STREQUAL "loginserver")
    execute_process(COMMAND "${APP}" --check --config "${appDir}/${NAME}.conf.dist" ${quietOptions} "--set=LoginDatabaseInfo=not a connection string"
        WORKING_DIRECTORY "${WORKDIR}" RESULT_VARIABLE badResult OUTPUT_VARIABLE badOutput ERROR_VARIABLE badError TIMEOUT 30)
    if(NOT badResult EQUAL 1)
        message(FATAL_ERROR "loginserver with a bad LoginDatabaseInfo exited ${badResult}: ${badOutput}${badError}")
    endif()
    if(NOT badOutput MATCHES "LoginDatabaseInfo is not a valid connection string")
        message(FATAL_ERROR "loginserver with a bad LoginDatabaseInfo did not explain why: ${badOutput}${badError}")
    endif()
endif()
