/*
 * Project Ambrose by Imjustchico
 * Generated from design/tokens.json: every token as a typed constant, with the contrast each documented pair reaches.
 */

export const primitiveColors = {
    "ground": "#0B1020",
    "chrome": "#070B16",
    "panel": "#131B31",
    "sunken": "#0E1527",
    "border": "#1B2540",
    "border-strong": "#22304F",
    "text": "#F2E8D5",
    "text-muted": "#A8B6D4",
    "text-faint": "#8798BC",
    "gold": "#E4B457",
    "gold-deep": "#B98A2D",
    "teal": "#5FD3C4",
    "violet": "#C77DFF",
    "ember": "#E2725B",
    "parchment": "#F4EAD5",
    "parchment-raised": "#FFFDF7",
    "parchment-sunken": "#EADFC4",
    "parchment-chrome": "#FBF5E7",
    "parchment-border": "#D9CBAB",
    "parchment-border-strong": "#C3AE86",
    "ink": "#1B1608",
    "ink-muted": "#4A3F28",
    "ink-faint": "#5F5238",
    "gold-dark": "#7A5A12",
    "gold-darkest": "#6A4E0F",
    "teal-dark": "#0F6F63",
    "edge-control": "#546AA5",
    "value-number": "#D1988F",
    "value-number-dark": "#521915",
    "value-text": "#B4A5FB",
    "value-text-dark": "#172075",
    "value-name": "#8EE4A1",
    "value-name-dark": "#043415",
    "value-address": "#28BDFA",
    "value-address-dark": "#00435C",
    "value-setting": "#E07AAE",
    "value-setting-dark": "#5B013A",
    "violet-dark": "#6B2FA0",
    "ember-dark": "#A33A25",
} as const;

export type PrimitiveColorName = keyof typeof primitiveColors;

export const semanticColors = {
    dark: {
        "surface-page": "#0B1020",
        "surface-card": "#131B31",
        "surface-sunken": "#0E1527",
        "surface-chrome": "#070B16",
        "edge-quiet": "#1B2540",
        "edge-strong": "#22304F",
        "edge-control": "#546AA5",
        "value-number": "#D1988F",
        "value-text": "#B4A5FB",
        "value-name": "#8EE4A1",
        "value-address": "#28BDFA",
        "value-setting": "#E07AAE",
        "fg-body": "#F2E8D5",
        "fg-muted": "#A8B6D4",
        "fg-faint": "#8798BC",
        "action": "#E4B457",
        "action-pressed": "#B98A2D",
        "state-healthy": "#5FD3C4",
        "state-waiting": "#E4B457",
        "state-wrong": "#E2725B",
        "state-unknown": "#8798BC",
        "mine": "#C77DFF",
        "focus-ring": "#E4B457",
    },
    light: {
        "surface-page": "#F4EAD5",
        "surface-card": "#FFFDF7",
        "surface-sunken": "#EADFC4",
        "surface-chrome": "#FBF5E7",
        "edge-quiet": "#D9CBAB",
        "edge-strong": "#C3AE86",
        "edge-control": "#546AA5",
        "value-number": "#521915",
        "value-text": "#172075",
        "value-name": "#043415",
        "value-address": "#00435C",
        "value-setting": "#5B013A",
        "fg-body": "#1B1608",
        "fg-muted": "#4A3F28",
        "fg-faint": "#5F5238",
        "action": "#7A5A12",
        "action-pressed": "#6A4E0F",
        "state-healthy": "#0F6F63",
        "state-waiting": "#7A5A12",
        "state-wrong": "#A33A25",
        "state-unknown": "#5F5238",
        "mine": "#6B2FA0",
        "focus-ring": "#7A5A12",
    },
} as const;

export type SemanticColorName = keyof typeof semanticColors.dark;

export const componentColors = {
    dark: {
        "fill-action": "#E4B457",
        "fill-action-pressed": "#B98A2D",
        "fill-danger": "#E2725B",
        "fill-healthy": "#5FD3C4",
        "fill-mine": "#C77DFF",
        "on-fill": "#0B1020",
    },
    light: {
        "fill-action": "#E4B457",
        "fill-action-pressed": "#B98A2D",
        "fill-danger": "#E2725B",
        "fill-healthy": "#5FD3C4",
        "fill-mine": "#C77DFF",
        "on-fill": "#0B1020",
    },
} as const;

export const seriesColors = {
    dark: ["#C9503F", "#B8C24E", "#79C98A", "#2A8F7C", "#7D6BD6", "#A560A5", "#E1A6C4"],
    light: ["#B45A5A", "#8A7A22", "#2F5A22", "#2D7E9C", "#3B3AA8", "#6A2A86", "#8E2A5C"],
} as const;

export const space = {
    "4": "4px",
    "6": "6px",
    "8": "8px",
    "10": "10px",
    "12": "12px",
    "14": "14px",
    "16": "16px",
    "20": "20px",
    "22": "22px",
    "28": "28px",
    "34": "34px",
    "40": "40px",
    "44": "44px",
} as const;

export const radius = {
    "control": "6px",
    "input": "8px",
    "card": "10px",
    "action": "12px",
    "pill": "999px",
} as const;

export const fontSize = {
    "11": "11px",
    "12": "12px",
    "13": "13px",
    "15": "15px",
    "17": "17px",
    "21": "21px",
    "26": "26px",
    "34": "34px",
    "44": "44px",
    "56": "56px",
} as const;

export const fontFamily = {
    "display": "\"Cormorant Garamond\", Georgia, \"Times New Roman\", serif",
    "interface": "Karla, \"Segoe UI\", \"Helvetica Neue\", Arial, sans-serif",
    "mono": "\"JetBrains Mono\", \"Cascadia Mono\", Consolas, \"DejaVu Sans Mono\", monospace",
} as const;

export const componentSize = {
    "chrome-bar": "44px",
    "side-bar": "236px",
    "touch-target": "44px",
    "dialog": "520px",
    "focus-ring": "2px",
    "border": "1px",
    "action-inset": "3px",
} as const;

export const durationMs = {
    "flip": 90,
    "hover": 120,
    "panel": 200,
    "screen": 320,
} as const;

export type DurationName = keyof typeof durationMs;

export const easing = {
    "standard": "cubic-bezier(0.2, 0, 0, 1)",
    "exit": "cubic-bezier(0.4, 0, 1, 1)",
} as const;

export const themes = ["dark", "light"] as const;

export type Theme = (typeof themes)[number];

export type ContrastPair = {
    foreground: string;
    background: string;
    theme: Theme;
    ratio: number;
    minimum: number;
    note: string;
};

export const contrastPairs: readonly ContrastPair[] = [
    { foreground: "semantic.color.value-number", background: "semantic.color.surface-page", theme: "dark", ratio: 7.75, minimum: 4.5, note: "A value highlighted inside a message, on every surface" },
    { foreground: "semantic.color.value-number", background: "semantic.color.surface-page", theme: "light", ratio: 11.65, minimum: 4.5, note: "A value highlighted inside a message, on every surface" },
    { foreground: "semantic.color.value-number", background: "semantic.color.surface-card", theme: "dark", ratio: 7.0, minimum: 4.5, note: "A value highlighted inside a message, on every surface" },
    { foreground: "semantic.color.value-number", background: "semantic.color.surface-card", theme: "light", ratio: 13.68, minimum: 4.5, note: "A value highlighted inside a message, on every surface" },
    { foreground: "semantic.color.value-number", background: "semantic.color.surface-sunken", theme: "dark", ratio: 7.44, minimum: 4.5, note: "A value highlighted inside a message, on every surface" },
    { foreground: "semantic.color.value-number", background: "semantic.color.surface-sunken", theme: "light", ratio: 10.51, minimum: 4.5, note: "A value highlighted inside a message, on every surface" },
    { foreground: "semantic.color.value-number", background: "semantic.color.surface-chrome", theme: "dark", ratio: 8.05, minimum: 4.5, note: "A value highlighted inside a message, on every surface" },
    { foreground: "semantic.color.value-number", background: "semantic.color.surface-chrome", theme: "light", ratio: 12.8, minimum: 4.5, note: "A value highlighted inside a message, on every surface" },
    { foreground: "semantic.color.value-text", background: "semantic.color.surface-page", theme: "dark", ratio: 8.76, minimum: 4.5, note: "A value highlighted inside a message, on every surface" },
    { foreground: "semantic.color.value-text", background: "semantic.color.surface-page", theme: "light", ratio: 11.72, minimum: 4.5, note: "A value highlighted inside a message, on every surface" },
    { foreground: "semantic.color.value-text", background: "semantic.color.surface-card", theme: "dark", ratio: 7.91, minimum: 4.5, note: "A value highlighted inside a message, on every surface" },
    { foreground: "semantic.color.value-text", background: "semantic.color.surface-card", theme: "light", ratio: 13.76, minimum: 4.5, note: "A value highlighted inside a message, on every surface" },
    { foreground: "semantic.color.value-text", background: "semantic.color.surface-sunken", theme: "dark", ratio: 8.41, minimum: 4.5, note: "A value highlighted inside a message, on every surface" },
    { foreground: "semantic.color.value-text", background: "semantic.color.surface-sunken", theme: "light", ratio: 10.57, minimum: 4.5, note: "A value highlighted inside a message, on every surface" },
    { foreground: "semantic.color.value-text", background: "semantic.color.surface-chrome", theme: "dark", ratio: 9.09, minimum: 4.5, note: "A value highlighted inside a message, on every surface" },
    { foreground: "semantic.color.value-text", background: "semantic.color.surface-chrome", theme: "light", ratio: 12.88, minimum: 4.5, note: "A value highlighted inside a message, on every surface" },
    { foreground: "semantic.color.value-name", background: "semantic.color.surface-page", theme: "dark", ratio: 12.41, minimum: 4.5, note: "A value highlighted inside a message, on every surface" },
    { foreground: "semantic.color.value-name", background: "semantic.color.surface-page", theme: "light", ratio: 11.66, minimum: 4.5, note: "A value highlighted inside a message, on every surface" },
    { foreground: "semantic.color.value-name", background: "semantic.color.surface-card", theme: "dark", ratio: 11.2, minimum: 4.5, note: "A value highlighted inside a message, on every surface" },
    { foreground: "semantic.color.value-name", background: "semantic.color.surface-card", theme: "light", ratio: 13.7, minimum: 4.5, note: "A value highlighted inside a message, on every surface" },
    { foreground: "semantic.color.value-name", background: "semantic.color.surface-sunken", theme: "dark", ratio: 11.91, minimum: 4.5, note: "A value highlighted inside a message, on every surface" },
    { foreground: "semantic.color.value-name", background: "semantic.color.surface-sunken", theme: "light", ratio: 10.52, minimum: 4.5, note: "A value highlighted inside a message, on every surface" },
    { foreground: "semantic.color.value-name", background: "semantic.color.surface-chrome", theme: "dark", ratio: 12.88, minimum: 4.5, note: "A value highlighted inside a message, on every surface" },
    { foreground: "semantic.color.value-name", background: "semantic.color.surface-chrome", theme: "light", ratio: 12.82, minimum: 4.5, note: "A value highlighted inside a message, on every surface" },
    { foreground: "semantic.color.value-address", background: "semantic.color.surface-page", theme: "dark", ratio: 8.79, minimum: 4.5, note: "A value highlighted inside a message, on every surface" },
    { foreground: "semantic.color.value-address", background: "semantic.color.surface-page", theme: "light", ratio: 8.98, minimum: 4.5, note: "A value highlighted inside a message, on every surface" },
    { foreground: "semantic.color.value-address", background: "semantic.color.surface-card", theme: "dark", ratio: 7.93, minimum: 4.5, note: "A value highlighted inside a message, on every surface" },
    { foreground: "semantic.color.value-address", background: "semantic.color.surface-card", theme: "light", ratio: 10.55, minimum: 4.5, note: "A value highlighted inside a message, on every surface" },
    { foreground: "semantic.color.value-address", background: "semantic.color.surface-sunken", theme: "dark", ratio: 8.44, minimum: 4.5, note: "A value highlighted inside a message, on every surface" },
    { foreground: "semantic.color.value-address", background: "semantic.color.surface-sunken", theme: "light", ratio: 8.1, minimum: 4.5, note: "A value highlighted inside a message, on every surface" },
    { foreground: "semantic.color.value-address", background: "semantic.color.surface-chrome", theme: "dark", ratio: 9.12, minimum: 4.5, note: "A value highlighted inside a message, on every surface" },
    { foreground: "semantic.color.value-address", background: "semantic.color.surface-chrome", theme: "light", ratio: 9.87, minimum: 4.5, note: "A value highlighted inside a message, on every surface" },
    { foreground: "semantic.color.value-setting", background: "semantic.color.surface-page", theme: "dark", ratio: 6.82, minimum: 4.5, note: "A value highlighted inside a message, on every surface" },
    { foreground: "semantic.color.value-setting", background: "semantic.color.surface-page", theme: "light", ratio: 11.64, minimum: 4.5, note: "A value highlighted inside a message, on every surface" },
    { foreground: "semantic.color.value-setting", background: "semantic.color.surface-card", theme: "dark", ratio: 6.16, minimum: 4.5, note: "A value highlighted inside a message, on every surface" },
    { foreground: "semantic.color.value-setting", background: "semantic.color.surface-card", theme: "light", ratio: 13.67, minimum: 4.5, note: "A value highlighted inside a message, on every surface" },
    { foreground: "semantic.color.value-setting", background: "semantic.color.surface-sunken", theme: "dark", ratio: 6.55, minimum: 4.5, note: "A value highlighted inside a message, on every surface" },
    { foreground: "semantic.color.value-setting", background: "semantic.color.surface-sunken", theme: "light", ratio: 10.5, minimum: 4.5, note: "A value highlighted inside a message, on every surface" },
    { foreground: "semantic.color.value-setting", background: "semantic.color.surface-chrome", theme: "dark", ratio: 7.08, minimum: 4.5, note: "A value highlighted inside a message, on every surface" },
    { foreground: "semantic.color.value-setting", background: "semantic.color.surface-chrome", theme: "light", ratio: 12.79, minimum: 4.5, note: "A value highlighted inside a message, on every surface" },
    { foreground: "semantic.color.edge-control", background: "semantic.color.surface-page", theme: "dark", ratio: 3.59, minimum: 3.0, note: "A control edge on every surface it may sit on" },
    { foreground: "semantic.color.edge-control", background: "semantic.color.surface-page", theme: "light", ratio: 4.41, minimum: 3.0, note: "A control edge on every surface it may sit on" },
    { foreground: "semantic.color.edge-control", background: "semantic.color.surface-card", theme: "dark", ratio: 3.24, minimum: 3.0, note: "A control edge on every surface it may sit on" },
    { foreground: "semantic.color.edge-control", background: "semantic.color.surface-card", theme: "light", ratio: 5.18, minimum: 3.0, note: "A control edge on every surface it may sit on" },
    { foreground: "semantic.color.edge-control", background: "semantic.color.surface-sunken", theme: "dark", ratio: 3.45, minimum: 3.0, note: "A control edge on every surface it may sit on" },
    { foreground: "semantic.color.edge-control", background: "semantic.color.surface-sunken", theme: "light", ratio: 3.98, minimum: 3.0, note: "A control edge on every surface it may sit on" },
    { foreground: "semantic.color.edge-control", background: "semantic.color.surface-chrome", theme: "dark", ratio: 3.73, minimum: 3.0, note: "A control edge on every surface it may sit on" },
    { foreground: "semantic.color.edge-control", background: "semantic.color.surface-chrome", theme: "light", ratio: 4.85, minimum: 3.0, note: "A control edge on every surface it may sit on" },
    { foreground: "semantic.color.fg-body", background: "semantic.color.surface-page", theme: "dark", ratio: 15.58, minimum: 4.5, note: "Body, secondary and hint text on every surface" },
    { foreground: "semantic.color.fg-body", background: "semantic.color.surface-page", theme: "light", ratio: 15.09, minimum: 4.5, note: "Body, secondary and hint text on every surface" },
    { foreground: "semantic.color.fg-body", background: "semantic.color.surface-card", theme: "dark", ratio: 14.06, minimum: 4.5, note: "Body, secondary and hint text on every surface" },
    { foreground: "semantic.color.fg-body", background: "semantic.color.surface-card", theme: "light", ratio: 17.72, minimum: 4.5, note: "Body, secondary and hint text on every surface" },
    { foreground: "semantic.color.fg-body", background: "semantic.color.surface-sunken", theme: "dark", ratio: 14.96, minimum: 4.5, note: "Body, secondary and hint text on every surface" },
    { foreground: "semantic.color.fg-body", background: "semantic.color.surface-sunken", theme: "light", ratio: 13.61, minimum: 4.5, note: "Body, secondary and hint text on every surface" },
    { foreground: "semantic.color.fg-body", background: "semantic.color.surface-chrome", theme: "dark", ratio: 16.17, minimum: 4.5, note: "Body, secondary and hint text on every surface" },
    { foreground: "semantic.color.fg-body", background: "semantic.color.surface-chrome", theme: "light", ratio: 16.58, minimum: 4.5, note: "Body, secondary and hint text on every surface" },
    { foreground: "semantic.color.fg-muted", background: "semantic.color.surface-page", theme: "dark", ratio: 9.29, minimum: 4.5, note: "Body, secondary and hint text on every surface" },
    { foreground: "semantic.color.fg-muted", background: "semantic.color.surface-page", theme: "light", ratio: 8.65, minimum: 4.5, note: "Body, secondary and hint text on every surface" },
    { foreground: "semantic.color.fg-muted", background: "semantic.color.surface-card", theme: "dark", ratio: 8.39, minimum: 4.5, note: "Body, secondary and hint text on every surface" },
    { foreground: "semantic.color.fg-muted", background: "semantic.color.surface-card", theme: "light", ratio: 10.16, minimum: 4.5, note: "Body, secondary and hint text on every surface" },
    { foreground: "semantic.color.fg-muted", background: "semantic.color.surface-sunken", theme: "dark", ratio: 8.92, minimum: 4.5, note: "Body, secondary and hint text on every surface" },
    { foreground: "semantic.color.fg-muted", background: "semantic.color.surface-sunken", theme: "light", ratio: 7.8, minimum: 4.5, note: "Body, secondary and hint text on every surface" },
    { foreground: "semantic.color.fg-muted", background: "semantic.color.surface-chrome", theme: "dark", ratio: 9.65, minimum: 4.5, note: "Body, secondary and hint text on every surface" },
    { foreground: "semantic.color.fg-muted", background: "semantic.color.surface-chrome", theme: "light", ratio: 9.5, minimum: 4.5, note: "Body, secondary and hint text on every surface" },
    { foreground: "semantic.color.fg-faint", background: "semantic.color.surface-page", theme: "dark", ratio: 6.53, minimum: 4.5, note: "Body, secondary and hint text on every surface" },
    { foreground: "semantic.color.fg-faint", background: "semantic.color.surface-page", theme: "light", ratio: 6.39, minimum: 4.5, note: "Body, secondary and hint text on every surface" },
    { foreground: "semantic.color.fg-faint", background: "semantic.color.surface-card", theme: "dark", ratio: 5.9, minimum: 4.5, note: "Body, secondary and hint text on every surface" },
    { foreground: "semantic.color.fg-faint", background: "semantic.color.surface-card", theme: "light", ratio: 7.51, minimum: 4.5, note: "Body, secondary and hint text on every surface" },
    { foreground: "semantic.color.fg-faint", background: "semantic.color.surface-sunken", theme: "dark", ratio: 6.27, minimum: 4.5, note: "Body, secondary and hint text on every surface" },
    { foreground: "semantic.color.fg-faint", background: "semantic.color.surface-sunken", theme: "light", ratio: 5.76, minimum: 4.5, note: "Body, secondary and hint text on every surface" },
    { foreground: "semantic.color.fg-faint", background: "semantic.color.surface-chrome", theme: "dark", ratio: 6.78, minimum: 4.5, note: "Body, secondary and hint text on every surface" },
    { foreground: "semantic.color.fg-faint", background: "semantic.color.surface-chrome", theme: "light", ratio: 7.02, minimum: 4.5, note: "Body, secondary and hint text on every surface" },
    { foreground: "semantic.color.action", background: "semantic.color.surface-page", theme: "dark", ratio: 9.89, minimum: 4.5, note: "A state word, an action and an owner mark on every surface" },
    { foreground: "semantic.color.action", background: "semantic.color.surface-page", theme: "light", ratio: 5.33, minimum: 4.5, note: "A state word, an action and an owner mark on every surface" },
    { foreground: "semantic.color.action", background: "semantic.color.surface-card", theme: "dark", ratio: 8.92, minimum: 4.5, note: "A state word, an action and an owner mark on every surface" },
    { foreground: "semantic.color.action", background: "semantic.color.surface-card", theme: "light", ratio: 6.26, minimum: 4.5, note: "A state word, an action and an owner mark on every surface" },
    { foreground: "semantic.color.action", background: "semantic.color.surface-sunken", theme: "dark", ratio: 9.49, minimum: 4.5, note: "A state word, an action and an owner mark on every surface" },
    { foreground: "semantic.color.action", background: "semantic.color.surface-sunken", theme: "light", ratio: 4.81, minimum: 4.5, note: "A state word, an action and an owner mark on every surface" },
    { foreground: "semantic.color.action", background: "semantic.color.surface-chrome", theme: "dark", ratio: 10.26, minimum: 4.5, note: "A state word, an action and an owner mark on every surface" },
    { foreground: "semantic.color.action", background: "semantic.color.surface-chrome", theme: "light", ratio: 5.86, minimum: 4.5, note: "A state word, an action and an owner mark on every surface" },
    { foreground: "semantic.color.action-pressed", background: "semantic.color.surface-page", theme: "dark", ratio: 6.07, minimum: 4.5, note: "A state word, an action and an owner mark on every surface" },
    { foreground: "semantic.color.action-pressed", background: "semantic.color.surface-page", theme: "light", ratio: 6.49, minimum: 4.5, note: "A state word, an action and an owner mark on every surface" },
    { foreground: "semantic.color.action-pressed", background: "semantic.color.surface-card", theme: "dark", ratio: 5.48, minimum: 4.5, note: "A state word, an action and an owner mark on every surface" },
    { foreground: "semantic.color.action-pressed", background: "semantic.color.surface-card", theme: "light", ratio: 7.62, minimum: 4.5, note: "A state word, an action and an owner mark on every surface" },
    { foreground: "semantic.color.action-pressed", background: "semantic.color.surface-sunken", theme: "dark", ratio: 5.83, minimum: 4.5, note: "A state word, an action and an owner mark on every surface" },
    { foreground: "semantic.color.action-pressed", background: "semantic.color.surface-sunken", theme: "light", ratio: 5.85, minimum: 4.5, note: "A state word, an action and an owner mark on every surface" },
    { foreground: "semantic.color.action-pressed", background: "semantic.color.surface-chrome", theme: "dark", ratio: 6.3, minimum: 4.5, note: "A state word, an action and an owner mark on every surface" },
    { foreground: "semantic.color.action-pressed", background: "semantic.color.surface-chrome", theme: "light", ratio: 7.13, minimum: 4.5, note: "A state word, an action and an owner mark on every surface" },
    { foreground: "semantic.color.state-healthy", background: "semantic.color.surface-page", theme: "dark", ratio: 10.46, minimum: 4.5, note: "A state word, an action and an owner mark on every surface" },
    { foreground: "semantic.color.state-healthy", background: "semantic.color.surface-page", theme: "light", ratio: 5.06, minimum: 4.5, note: "A state word, an action and an owner mark on every surface" },
    { foreground: "semantic.color.state-healthy", background: "semantic.color.surface-card", theme: "dark", ratio: 9.44, minimum: 4.5, note: "A state word, an action and an owner mark on every surface" },
    { foreground: "semantic.color.state-healthy", background: "semantic.color.surface-card", theme: "light", ratio: 5.94, minimum: 4.5, note: "A state word, an action and an owner mark on every surface" },
    { foreground: "semantic.color.state-healthy", background: "semantic.color.surface-sunken", theme: "dark", ratio: 10.04, minimum: 4.5, note: "A state word, an action and an owner mark on every surface" },
    { foreground: "semantic.color.state-healthy", background: "semantic.color.surface-sunken", theme: "light", ratio: 4.56, minimum: 4.5, note: "A state word, an action and an owner mark on every surface" },
    { foreground: "semantic.color.state-healthy", background: "semantic.color.surface-chrome", theme: "dark", ratio: 10.86, minimum: 4.5, note: "A state word, an action and an owner mark on every surface" },
    { foreground: "semantic.color.state-healthy", background: "semantic.color.surface-chrome", theme: "light", ratio: 5.56, minimum: 4.5, note: "A state word, an action and an owner mark on every surface" },
    { foreground: "semantic.color.state-waiting", background: "semantic.color.surface-page", theme: "dark", ratio: 9.89, minimum: 4.5, note: "A state word, an action and an owner mark on every surface" },
    { foreground: "semantic.color.state-waiting", background: "semantic.color.surface-page", theme: "light", ratio: 5.33, minimum: 4.5, note: "A state word, an action and an owner mark on every surface" },
    { foreground: "semantic.color.state-waiting", background: "semantic.color.surface-card", theme: "dark", ratio: 8.92, minimum: 4.5, note: "A state word, an action and an owner mark on every surface" },
    { foreground: "semantic.color.state-waiting", background: "semantic.color.surface-card", theme: "light", ratio: 6.26, minimum: 4.5, note: "A state word, an action and an owner mark on every surface" },
    { foreground: "semantic.color.state-waiting", background: "semantic.color.surface-sunken", theme: "dark", ratio: 9.49, minimum: 4.5, note: "A state word, an action and an owner mark on every surface" },
    { foreground: "semantic.color.state-waiting", background: "semantic.color.surface-sunken", theme: "light", ratio: 4.81, minimum: 4.5, note: "A state word, an action and an owner mark on every surface" },
    { foreground: "semantic.color.state-waiting", background: "semantic.color.surface-chrome", theme: "dark", ratio: 10.26, minimum: 4.5, note: "A state word, an action and an owner mark on every surface" },
    { foreground: "semantic.color.state-waiting", background: "semantic.color.surface-chrome", theme: "light", ratio: 5.86, minimum: 4.5, note: "A state word, an action and an owner mark on every surface" },
    { foreground: "semantic.color.state-wrong", background: "semantic.color.surface-page", theme: "dark", ratio: 6.12, minimum: 4.5, note: "A state word, an action and an owner mark on every surface" },
    { foreground: "semantic.color.state-wrong", background: "semantic.color.surface-page", theme: "light", ratio: 5.51, minimum: 4.5, note: "A state word, an action and an owner mark on every surface" },
    { foreground: "semantic.color.state-wrong", background: "semantic.color.surface-card", theme: "dark", ratio: 5.53, minimum: 4.5, note: "A state word, an action and an owner mark on every surface" },
    { foreground: "semantic.color.state-wrong", background: "semantic.color.surface-card", theme: "light", ratio: 6.47, minimum: 4.5, note: "A state word, an action and an owner mark on every surface" },
    { foreground: "semantic.color.state-wrong", background: "semantic.color.surface-sunken", theme: "dark", ratio: 5.88, minimum: 4.5, note: "A state word, an action and an owner mark on every surface" },
    { foreground: "semantic.color.state-wrong", background: "semantic.color.surface-sunken", theme: "light", ratio: 4.97, minimum: 4.5, note: "A state word, an action and an owner mark on every surface" },
    { foreground: "semantic.color.state-wrong", background: "semantic.color.surface-chrome", theme: "dark", ratio: 6.36, minimum: 4.5, note: "A state word, an action and an owner mark on every surface" },
    { foreground: "semantic.color.state-wrong", background: "semantic.color.surface-chrome", theme: "light", ratio: 6.06, minimum: 4.5, note: "A state word, an action and an owner mark on every surface" },
    { foreground: "semantic.color.state-unknown", background: "semantic.color.surface-page", theme: "dark", ratio: 6.53, minimum: 4.5, note: "A state word, an action and an owner mark on every surface" },
    { foreground: "semantic.color.state-unknown", background: "semantic.color.surface-page", theme: "light", ratio: 6.39, minimum: 4.5, note: "A state word, an action and an owner mark on every surface" },
    { foreground: "semantic.color.state-unknown", background: "semantic.color.surface-card", theme: "dark", ratio: 5.9, minimum: 4.5, note: "A state word, an action and an owner mark on every surface" },
    { foreground: "semantic.color.state-unknown", background: "semantic.color.surface-card", theme: "light", ratio: 7.51, minimum: 4.5, note: "A state word, an action and an owner mark on every surface" },
    { foreground: "semantic.color.state-unknown", background: "semantic.color.surface-sunken", theme: "dark", ratio: 6.27, minimum: 4.5, note: "A state word, an action and an owner mark on every surface" },
    { foreground: "semantic.color.state-unknown", background: "semantic.color.surface-sunken", theme: "light", ratio: 5.76, minimum: 4.5, note: "A state word, an action and an owner mark on every surface" },
    { foreground: "semantic.color.state-unknown", background: "semantic.color.surface-chrome", theme: "dark", ratio: 6.78, minimum: 4.5, note: "A state word, an action and an owner mark on every surface" },
    { foreground: "semantic.color.state-unknown", background: "semantic.color.surface-chrome", theme: "light", ratio: 7.02, minimum: 4.5, note: "A state word, an action and an owner mark on every surface" },
    { foreground: "semantic.color.mine", background: "semantic.color.surface-page", theme: "dark", ratio: 7.04, minimum: 4.5, note: "A state word, an action and an owner mark on every surface" },
    { foreground: "semantic.color.mine", background: "semantic.color.surface-page", theme: "light", ratio: 6.92, minimum: 4.5, note: "A state word, an action and an owner mark on every surface" },
    { foreground: "semantic.color.mine", background: "semantic.color.surface-card", theme: "dark", ratio: 6.35, minimum: 4.5, note: "A state word, an action and an owner mark on every surface" },
    { foreground: "semantic.color.mine", background: "semantic.color.surface-card", theme: "light", ratio: 8.13, minimum: 4.5, note: "A state word, an action and an owner mark on every surface" },
    { foreground: "semantic.color.mine", background: "semantic.color.surface-sunken", theme: "dark", ratio: 6.76, minimum: 4.5, note: "A state word, an action and an owner mark on every surface" },
    { foreground: "semantic.color.mine", background: "semantic.color.surface-sunken", theme: "light", ratio: 6.24, minimum: 4.5, note: "A state word, an action and an owner mark on every surface" },
    { foreground: "semantic.color.mine", background: "semantic.color.surface-chrome", theme: "dark", ratio: 7.31, minimum: 4.5, note: "A state word, an action and an owner mark on every surface" },
    { foreground: "semantic.color.mine", background: "semantic.color.surface-chrome", theme: "light", ratio: 7.61, minimum: 4.5, note: "A state word, an action and an owner mark on every surface" },
    { foreground: "semantic.color.focus-ring", background: "semantic.color.surface-page", theme: "dark", ratio: 9.89, minimum: 3.0, note: "The focus ring, which is an indicator rather than text" },
    { foreground: "semantic.color.focus-ring", background: "semantic.color.surface-page", theme: "light", ratio: 5.33, minimum: 3.0, note: "The focus ring, which is an indicator rather than text" },
    { foreground: "semantic.color.focus-ring", background: "semantic.color.surface-card", theme: "dark", ratio: 8.92, minimum: 3.0, note: "The focus ring, which is an indicator rather than text" },
    { foreground: "semantic.color.focus-ring", background: "semantic.color.surface-card", theme: "light", ratio: 6.26, minimum: 3.0, note: "The focus ring, which is an indicator rather than text" },
    { foreground: "semantic.color.focus-ring", background: "semantic.color.surface-sunken", theme: "dark", ratio: 9.49, minimum: 3.0, note: "The focus ring, which is an indicator rather than text" },
    { foreground: "semantic.color.focus-ring", background: "semantic.color.surface-sunken", theme: "light", ratio: 4.81, minimum: 3.0, note: "The focus ring, which is an indicator rather than text" },
    { foreground: "semantic.color.focus-ring", background: "semantic.color.surface-chrome", theme: "dark", ratio: 10.26, minimum: 3.0, note: "The focus ring, which is an indicator rather than text" },
    { foreground: "semantic.color.focus-ring", background: "semantic.color.surface-chrome", theme: "light", ratio: 5.86, minimum: 3.0, note: "The focus ring, which is an indicator rather than text" },
    { foreground: "component.color.on-fill", background: "component.color.fill-action", theme: "dark", ratio: 9.89, minimum: 4.5, note: "The label on a filled accent" },
    { foreground: "component.color.on-fill", background: "component.color.fill-action", theme: "light", ratio: 9.89, minimum: 4.5, note: "The label on a filled accent" },
    { foreground: "component.color.on-fill", background: "component.color.fill-action-pressed", theme: "dark", ratio: 6.07, minimum: 4.5, note: "The label on a filled accent" },
    { foreground: "component.color.on-fill", background: "component.color.fill-action-pressed", theme: "light", ratio: 6.07, minimum: 4.5, note: "The label on a filled accent" },
    { foreground: "component.color.on-fill", background: "component.color.fill-danger", theme: "dark", ratio: 6.12, minimum: 4.5, note: "The label on a filled accent" },
    { foreground: "component.color.on-fill", background: "component.color.fill-danger", theme: "light", ratio: 6.12, minimum: 4.5, note: "The label on a filled accent" },
    { foreground: "component.color.on-fill", background: "component.color.fill-healthy", theme: "dark", ratio: 10.46, minimum: 4.5, note: "The label on a filled accent" },
    { foreground: "component.color.on-fill", background: "component.color.fill-healthy", theme: "light", ratio: 10.46, minimum: 4.5, note: "The label on a filled accent" },
    { foreground: "component.color.on-fill", background: "component.color.fill-mine", theme: "dark", ratio: 7.04, minimum: 4.5, note: "The label on a filled accent" },
    { foreground: "component.color.on-fill", background: "component.color.fill-mine", theme: "light", ratio: 7.04, minimum: 4.5, note: "The label on a filled accent" },
    { foreground: "series.color.1", background: "semantic.color.surface-page", theme: "dark", ratio: 4.24, minimum: 3.0, note: "A chart series, which is a graphical object rather than text" },
    { foreground: "series.color.1", background: "semantic.color.surface-page", theme: "light", ratio: 3.86, minimum: 3.0, note: "A chart series, which is a graphical object rather than text" },
    { foreground: "series.color.1", background: "semantic.color.surface-card", theme: "dark", ratio: 3.83, minimum: 3.0, note: "A chart series, which is a graphical object rather than text" },
    { foreground: "series.color.1", background: "semantic.color.surface-card", theme: "light", ratio: 4.54, minimum: 3.0, note: "A chart series, which is a graphical object rather than text" },
    { foreground: "series.color.2", background: "semantic.color.surface-page", theme: "dark", ratio: 9.8, minimum: 3.0, note: "A chart series, which is a graphical object rather than text" },
    { foreground: "series.color.2", background: "semantic.color.surface-page", theme: "light", ratio: 3.6, minimum: 3.0, note: "A chart series, which is a graphical object rather than text" },
    { foreground: "series.color.2", background: "semantic.color.surface-card", theme: "dark", ratio: 8.84, minimum: 3.0, note: "A chart series, which is a graphical object rather than text" },
    { foreground: "series.color.2", background: "semantic.color.surface-card", theme: "light", ratio: 4.22, minimum: 3.0, note: "A chart series, which is a graphical object rather than text" },
    { foreground: "series.color.3", background: "semantic.color.surface-page", theme: "dark", ratio: 9.5, minimum: 3.0, note: "A chart series, which is a graphical object rather than text" },
    { foreground: "series.color.3", background: "semantic.color.surface-page", theme: "light", ratio: 6.74, minimum: 3.0, note: "A chart series, which is a graphical object rather than text" },
    { foreground: "series.color.3", background: "semantic.color.surface-card", theme: "dark", ratio: 8.57, minimum: 3.0, note: "A chart series, which is a graphical object rather than text" },
    { foreground: "series.color.3", background: "semantic.color.surface-card", theme: "light", ratio: 7.92, minimum: 3.0, note: "A chart series, which is a graphical object rather than text" },
    { foreground: "series.color.4", background: "semantic.color.surface-page", theme: "dark", ratio: 4.79, minimum: 3.0, note: "A chart series, which is a graphical object rather than text" },
    { foreground: "series.color.4", background: "semantic.color.surface-page", theme: "light", ratio: 3.84, minimum: 3.0, note: "A chart series, which is a graphical object rather than text" },
    { foreground: "series.color.4", background: "semantic.color.surface-card", theme: "dark", ratio: 4.33, minimum: 3.0, note: "A chart series, which is a graphical object rather than text" },
    { foreground: "series.color.4", background: "semantic.color.surface-card", theme: "light", ratio: 4.51, minimum: 3.0, note: "A chart series, which is a graphical object rather than text" },
    { foreground: "series.color.5", background: "semantic.color.surface-page", theme: "dark", ratio: 4.46, minimum: 3.0, note: "A chart series, which is a graphical object rather than text" },
    { foreground: "series.color.5", background: "semantic.color.surface-page", theme: "light", ratio: 7.46, minimum: 3.0, note: "A chart series, which is a graphical object rather than text" },
    { foreground: "series.color.5", background: "semantic.color.surface-card", theme: "dark", ratio: 4.03, minimum: 3.0, note: "A chart series, which is a graphical object rather than text" },
    { foreground: "series.color.5", background: "semantic.color.surface-card", theme: "light", ratio: 8.76, minimum: 3.0, note: "A chart series, which is a graphical object rather than text" },
    { foreground: "series.color.6", background: "semantic.color.surface-page", theme: "dark", ratio: 4.34, minimum: 3.0, note: "A chart series, which is a graphical object rather than text" },
    { foreground: "series.color.6", background: "semantic.color.surface-page", theme: "light", ratio: 7.68, minimum: 3.0, note: "A chart series, which is a graphical object rather than text" },
    { foreground: "series.color.6", background: "semantic.color.surface-card", theme: "dark", ratio: 3.92, minimum: 3.0, note: "A chart series, which is a graphical object rather than text" },
    { foreground: "series.color.6", background: "semantic.color.surface-card", theme: "light", ratio: 9.02, minimum: 3.0, note: "A chart series, which is a graphical object rather than text" },
    { foreground: "series.color.7", background: "semantic.color.surface-page", theme: "dark", ratio: 9.42, minimum: 3.0, note: "A chart series, which is a graphical object rather than text" },
    { foreground: "series.color.7", background: "semantic.color.surface-page", theme: "light", ratio: 6.67, minimum: 3.0, note: "A chart series, which is a graphical object rather than text" },
    { foreground: "series.color.7", background: "semantic.color.surface-card", theme: "dark", ratio: 8.51, minimum: 3.0, note: "A chart series, which is a graphical object rather than text" },
    { foreground: "series.color.7", background: "semantic.color.surface-card", theme: "light", ratio: 7.83, minimum: 3.0, note: "A chart series, which is a graphical object rather than text" },
] as const;

export const terminalColors = {
    dark: {
        "surface-page": { hex: "#0B1020", index256: 233, index16: 0 },
        "surface-card": { hex: "#131B31", index256: 235, index16: 0 },
        "surface-sunken": { hex: "#0E1527", index256: 234, index16: 0 },
        "surface-chrome": { hex: "#070B16", index256: 233, index16: 0 },
        "edge-quiet": { hex: "#1B2540", index256: 236, index16: 8 },
        "edge-strong": { hex: "#22304F", index256: 237, index16: 8 },
        "edge-control": { hex: "#546AA5", index256: 61, index16: 4 },
        "value-number": { hex: "#D1988F", index256: 174, index16: 1 },
        "value-text": { hex: "#B4A5FB", index256: 147, index16: 4 },
        "value-name": { hex: "#8EE4A1", index256: 115, index16: 10 },
        "value-address": { hex: "#28BDFA", index256: 39, index16: 12 },
        "value-setting": { hex: "#E07AAE", index256: 175, index16: 5 },
        "fg-body": { hex: "#F2E8D5", index256: 7, index16: 15 },
        "fg-muted": { hex: "#A8B6D4", index256: 146, index16: 7 },
        "fg-faint": { hex: "#8798BC", index256: 103, index16: 8 },
        "action": { hex: "#E4B457", index256: 179, index16: 11 },
        "action-pressed": { hex: "#B98A2D", index256: 136, index16: 3 },
        "state-healthy": { hex: "#5FD3C4", index256: 79, index16: 14 },
        "state-waiting": { hex: "#E4B457", index256: 179, index16: 11 },
        "state-wrong": { hex: "#E2725B", index256: 167, index16: 9 },
        "state-unknown": { hex: "#8798BC", index256: 103, index16: 8 },
        "mine": { hex: "#C77DFF", index256: 177, index16: 13 },
        "focus-ring": { hex: "#E4B457", index256: 179, index16: 11 },
    },
    light: {
        "surface-page": { hex: "#F4EAD5", index256: 224, index16: 15 },
        "surface-card": { hex: "#FFFDF7", index256: 15, index16: 15 },
        "surface-sunken": { hex: "#EADFC4", index256: 253, index16: 7 },
        "surface-chrome": { hex: "#FBF5E7", index256: 255, index16: 15 },
        "edge-quiet": { hex: "#D9CBAB", index256: 187, index16: 7 },
        "edge-strong": { hex: "#C3AE86", index256: 144, index16: 7 },
        "edge-control": { hex: "#546AA5", index256: 61, index16: 4 },
        "value-number": { hex: "#521915", index256: 52, index16: 1 },
        "value-text": { hex: "#172075", index256: 17, index16: 4 },
        "value-name": { hex: "#043415", index256: 234, index16: 2 },
        "value-address": { hex: "#00435C", index256: 17, index16: 4 },
        "value-setting": { hex: "#5B013A", index256: 52, index16: 5 },
        "fg-body": { hex: "#1B1608", index256: 233, index16: 0 },
        "fg-muted": { hex: "#4A3F28", index256: 237, index16: 8 },
        "fg-faint": { hex: "#5F5238", index256: 58, index16: 8 },
        "action": { hex: "#7A5A12", index256: 94, index16: 3 },
        "action-pressed": { hex: "#6A4E0F", index256: 58, index16: 3 },
        "state-healthy": { hex: "#0F6F63", index256: 23, index16: 6 },
        "state-waiting": { hex: "#7A5A12", index256: 94, index16: 3 },
        "state-wrong": { hex: "#A33A25", index256: 124, index16: 1 },
        "state-unknown": { hex: "#5F5238", index256: 58, index16: 8 },
        "mine": { hex: "#6B2FA0", index256: 55, index16: 5 },
        "focus-ring": { hex: "#7A5A12", index256: 94, index16: 3 },
    },
} as const;
