# Project Ambrose by Imjustchico
# Finds every AddSC function in the script folders and every module's own loader, and writes the ScriptLoader source that calls them, so a script or a module is discovered by being there rather than by an edit to a core file.
function(ambrose_collect_script_loaders root pattern out_var)
    file(GLOB_RECURSE script_sources CONFIGURE_DEPENDS "${root}/*.cpp")
    set(found "")
    foreach(source IN LISTS script_sources)
        file(STRINGS "${source}" declarations REGEX "^[ \t]*void[ \t]+${pattern}[ \t]*\\([ \t]*\\)")
        foreach(declaration IN LISTS declarations)
            string(REGEX MATCH "${pattern}" name "${declaration}")
            if(name AND NOT name IN_LIST found)
                list(APPEND found "${name}")
            endif()
        endforeach()
    endforeach()
    list(SORT found)
    set(${out_var} "${found}" PARENT_SCOPE)
endfunction()

function(ambrose_write_script_loader out_file)
    ambrose_collect_script_loaders("${PROJECT_SOURCE_DIR}/src/server/scripts" "AddSC_[A-Za-z0-9_]+" script_loaders)
    ambrose_collect_script_loaders("${PROJECT_SOURCE_DIR}/modules" "Addmodules_[A-Za-z0-9_]+" module_loaders)

    set(declarations "")
    set(calls "")
    foreach(loader IN LISTS script_loaders module_loaders)
        string(APPEND declarations "void ${loader}();\n")
        string(APPEND calls "    ${loader}();\n")
    endforeach()

    list(LENGTH script_loaders script_count)
    list(LENGTH module_loaders module_count)
    set(AMBROSE_SCRIPT_DECLARATIONS "${declarations}")
    set(AMBROSE_SCRIPT_CALLS "${calls}")
    configure_file("${PROJECT_SOURCE_DIR}/src/cmake/ScriptLoader.cpp.in" "${out_file}" @ONLY)
    message(STATUS "Project Ambrose scripts: ${script_count} in src/server/scripts, ${module_count} in modules")
endfunction()

function(ambrose_collect_module_sources out_var)
    file(GLOB module_dirs "${PROJECT_SOURCE_DIR}/modules/*")
    set(sources "")
    foreach(module IN LISTS module_dirs)
        if(NOT IS_DIRECTORY "${module}/src")
            continue()
        endif()
        file(GLOB_RECURSE module_sources CONFIGURE_DEPENDS "${module}/src/*.cpp" "${module}/src/*.h")
        list(APPEND sources ${module_sources})
    endforeach()
    set(${out_var} "${sources}" PARENT_SCOPE)
endfunction()

function(ambrose_collect_module_include_dirs out_var)
    file(GLOB module_dirs "${PROJECT_SOURCE_DIR}/modules/*")
    set(dirs "")
    foreach(module IN LISTS module_dirs)
        if(NOT IS_DIRECTORY "${module}/src")
            continue()
        endif()
        ambrose_collect_include_dirs("${module}/src" module_dirs_for_one)
        list(APPEND dirs ${module_dirs_for_one})
    endforeach()
    set(${out_var} "${dirs}" PARENT_SCOPE)
endfunction()
